[Eth]
SyncMode = "snap"

[Node]
DataDir = "/mnt/bahamut"
HTTPHost = "0.0.0.0"
HTTPPort = 8547
HTTPVirtualHosts = ["*"]
HTTPModules = ["net", "web3", "eth", "txpool", "debug"]
AuthAddr = "localhost"
AuthPort = 8552
AuthVirtualHosts = ["*"]
WSHost = "0.0.0.0"
WSPort = 8548
WSModules = ["net", "web3", "eth", "txpool", "debug"]

[Node.P2P]
ListenAddr = ":30304"
